language: node_js
node_js:
  - 12.10.0

install:
  - cd backend; npm install  

script:
  - cd backend; npm test

after_success:
  - cd backend; npm run coveralls

branches:
  only:
  - master
  - develop