version: "3"
services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/app/
      - ./data:/usr/app/data
    command: npm start
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
    environment:
      APPENV_SERVER_HOST: ${BACKEND_API_HOST}
      APPENV_SERVER_PORT: ${BACKEND_API_PORT}
    user: ${UID}:${GID}

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_HOST: ${BACKEND_API_HOST}:${BACKEND_API_PORT}
    ports:
      - ${FRONTEND_PORT}:80

